// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnScanner.Api.Data;

#nullable disable

namespace VulnScanner.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703181422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("VulnScanner.Api.Models.ScanResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("VulnScanner.Api.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixedVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PkgName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnerabilityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanResultId");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("VulnScanner.Api.Models.Vulnerability", b =>
                {
                    b.HasOne("VulnScanner.Api.Models.ScanResult", "ScanResult")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("ScanResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanResult");
                });

            modelBuilder.Entity("VulnScanner.Api.Models.ScanResult", b =>
                {
                    b.Navigation("Vulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
